language: android

env:
  global:
  - secure: FHljLcVYogWvjvZ8iVohaMcyrOctba3dvb5BeRHh1efdN4V+IpJvpRbHtgAlaW3bT55++kQw33STk+YSepzwRm817JMu3U0qJ2sFQ9MXazmIkEBrAEUMDmfcBr2/LArtFED+T6gYCvom8lnq5LRQEkzkpREBnqkLcqzjtrP1IcZUoHlgaDZY0pyEopjN7cyPK8kOwvsqB3cavW7vk+LsTF+gm2ObTR+CnApJb1BilHsYMs3rF0mcAkhzzURL5B2hBaYQqGalSgx/JAzZyqLYbDnGcpbBs8YKbmsv5lT7EIYZ7pJaB92VphCy/8/QLkcI6irD4KuphXgFjzSo3lwFYokqEhNq53WQAAgg/3GoR+SdZyer0C5o58Fr/FWeM0bQ/5c0mCIVq0mVs61y8LsN0scAb2L6uqCdC0L4jfMToC2YRge8Fgxt9wUNb7DQf10iNrMNSyjQeiy9FBT8bwAJ15+AwukewU24Hcli3khZu7FzPil0A2U+L1SlDp+5R6TUUplfPaEyMZ+Cmu5qKwZ3RKo0pbsHrcww46mrxuaEwmOqnw2iBlIMPfxaMM+/OoPpecG0tippGmKc+vySulol+itlOtxx4kdI3XEVF3u/Xc9beq7hqouluKijsG/Kz07Mtxx7rKgX/B7W52XJ/kBhjTDsrLdBAERiBVVYtHMAvzs=

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25
    - sysimg-25

script:
- "./gradlew assembleDebug"

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && curl -F "file=@./app/build/outputs/apk/app-debug.apk" -F "token=${DEPLOYGATE_TOKEN}" -F "message=DeployGate Update" https://deploygate.com/api/users/shin178/apps
